version: '3.7'

services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    env_file:
      - '.env'
    ports:
      - '3306:3306'
    volumes:
      - './mysql-data:/var/lib/mysql'
