name: lambda-deployment-with-github-action-test

on: 
  push:
    branches:
        main # You can use any of your root or master branch name
  
jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
        
      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PORT: ${{ env.PORT }}
          JWT_SECRET: ${{env.JWT_SECRET}}
          DB_HOST: ${{env.DB_HOST}}
          DB_PORT: ${{env.DB_PORT}}
          DB_USER: ${{env.DB_USER}}
          DB_PASS: ${{env.DB_PASS}}
          DB_DATABASE: ${{env.DB_DATABASE}}
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}